### ISSUE TITLE
Error opening lab in Windows IDE

### ISSUE THREAD

**Issue by DaveWexler** [learn-co-curriculum/ruby-variable-assignment#73]
Hi,
When I click the open button in the lab to open the lab in the IDE for windows, I receive this error message in the IDE terminal:

bash: usr/local/rvm/gems/ruby-2.2.3/bin/learn: no such file or directory

It appears the lab is missing, I guess?  I can clone the lab to my local machine, but then I won't be able to run the local tests.

Thanks,
Dave W.

**Comment by AnnJohn** [comment]
hi @DaveWexler sorry for the issue that you're having. We use this space for issues specifically related to the curriculum content, and since this looks like a technical problem can you actually file a bug report? If you hover over your profile pic in Learn, you'll see a drop down menu with an option to file a bug report. You can also email support+ide@learn.co since this is a problem specifically related to the IDE. 

Thanks!
