### ISSUE TITLE
Warning message

### ISSUE THREAD

**Issue by shakeria07** [learn-co-curriculum/ruby-variable-assignment#82]
Hello,

I keep getting this message:

 2.3.1 :016 > [08:04:55] ~
// ♥ learn open ruby-variable-assignment-v-000
Looking for lesson...
WARNING: You are attempting to open a lesson that is beyond your current lesson.
Are you sure you want to continue? [Yn]:

I have gone backwards and forwards and still cannot figure out what I missed.

**Comment by morgvanny** [comment]
It's possible that the learn-co gem somehow got out of sync with the lesson you were on. It's ok to continue, and usually this type of thing resolves itself. If not, your best bet is to reach out via Ask a Question on the website, and we'll help you get it sorted it out. Since this issue doesn't pertain to this particular lab itself, I will close it now.
