### ISSUE TITLE
Ask A Question Still Does Not Work!!!!

### ISSUE THREAD

**Issue by Jhardrick** [learn-co-curriculum/ruby-variable-assignment#83]
It's 8:17 pm on the east coast and when I log into Learn.co and go to my lesson, the "Ask A Question" button is grayed out. This has happened to me every time I've logged in. Is there some issue going on?

**Comment by cjbrock** [comment]
Hey @Jhardrick! Ask A Question should be up and running. If you find yourself having issues, try clearing your cache and cookies, because sometimes we see issues where state gets stuck there. You can also try a hard refresh of the web page (command + shift + R on chrome on a mac). This article has some more helpful ideas! http://help.learn.co/instructional-support/receiving-course-support/ask-a-question-isnt-working

// <3 Corinna
